name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: shihlings/MCP2544WFDT-Breakout, shihlings/shihlings, shihlings/media, shihlings/github-stats, shihlings/adblock-server-web, shihlings/shihlings.github.io, shihlings/apsc100, shihlings/civl250, shihlings/cpen211-labs, shihlings/cpen211, ubc-cpen211/lab-3-l1c-shihlings, ubc-cpen211/lab-4-l1c-shihlings, ubc-cpen211/lab-5-l1c-shihlings, ubc-cpen211/lab-6-l1c-shihlings, ubc-cpen211/lab-7-l1c-shihlings, ubc-cpen211/lab-7-l1c-bonus-shihlings, shihlings/cpen311, shihlings/cpen311-labs, shihlings/cpsc259, shihlings/elec201, shihlings/elec202, shihlings/elec211, shihlings/elec221, shihlings/elec281, shihlings/elec291, shihlings/math
        EXCLUDED_LANGS: Stata, Yacc, Lex, Roff, Batchfile, HTML, Scheme, M4, Mathematica, Tcl
        EXCLUDE_FORKED_REPOS: true

    # Commit all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "jstrieb/github-stats"
        git config --global user.email "github-stats[bot]@jstrieb.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push
